// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzuoVQ7FVz2EL1wYyE1LG0mXVqi6-Ip4c',
    appId: '1:449650119462:web:9255738f529bf45ce5e7e7',
    messagingSenderId: '449650119462',
    projectId: 'tale-ce0cb',
    authDomain: 'tale-ce0cb.firebaseapp.com',
    storageBucket: 'tale-ce0cb.appspot.com',
    measurementId: 'G-HFVHXYZPHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLMbSQd-54g8AWEmD75KbaZ9DPqLxbbAg',
    appId: '1:449650119462:android:8c0ff217961186c2e5e7e7',
    messagingSenderId: '449650119462',
    projectId: 'tale-ce0cb',
    storageBucket: 'tale-ce0cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL2Of_5JOb4fIPymFjjMcNfjmaa8brtM0',
    appId: '1:449650119462:ios:c5adb4fcf68d84ece5e7e7',
    messagingSenderId: '449650119462',
    projectId: 'tale-ce0cb',
    storageBucket: 'tale-ce0cb.appspot.com',
    iosBundleId: 'com.example.tale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL2Of_5JOb4fIPymFjjMcNfjmaa8brtM0',
    appId: '1:449650119462:ios:c5adb4fcf68d84ece5e7e7',
    messagingSenderId: '449650119462',
    projectId: 'tale-ce0cb',
    storageBucket: 'tale-ce0cb.appspot.com',
    iosBundleId: 'com.example.tale',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzuoVQ7FVz2EL1wYyE1LG0mXVqi6-Ip4c',
    appId: '1:449650119462:web:5513df33d8980a5ee5e7e7',
    messagingSenderId: '449650119462',
    projectId: 'tale-ce0cb',
    authDomain: 'tale-ce0cb.firebaseapp.com',
    storageBucket: 'tale-ce0cb.appspot.com',
    measurementId: 'G-CHB9MV6RFM',
  );
}
